// @ts-ignore - this file is generated by OpenNext
import worker from './.open-next/worker.js';
import { runDatabaseBackup } from './lib/backup';
import { runDailyNotifications } from './lib/notifications';

export default {
  fetch: worker.fetch,
  async scheduled(controller: any, env: any, ctx: any) {
    if (controller.cron === "30 2 * * *") {
      ctx.waitUntil(
        runDailyNotifications(env)
          .then(result => console.log("Cron Notifications successful", result))
          .catch(err => console.error("Cron Notifications failed", err))
      );
    } else if (controller.cron === "30 18 * * *") {
      ctx.waitUntil(
        runDatabaseBackup(env.BACKUP_SECRET, env)
          .then(result => console.log("Cron Backup successful", result))
          .catch(err => console.error("Cron Backup failed", err))
      );
    }
  }
};
