// @ts-ignore - this file is generated by OpenNext
import worker from './.open-next/worker.js';
import { runDatabaseBackup } from './lib/backup';

export default {
  fetch: worker.fetch,
  async scheduled(controller: any, env: any, ctx: any) {
    ctx.waitUntil(
      runDatabaseBackup(env.BACKUP_SECRET, env)
        .then(result => console.log("Cron Backup successful", result))
        .catch(err => console.error("Cron Backup failed", err))
    );
  }
};
